# Action to build Docker image, run it and push when tagged
name: Docker actions

on:
  - push

jobs:
  # Builds and run GitHub Actions as intended
  docker-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build image and run
      uses: ./
      with:
        username: ${{ github.actor }}
        token: ${{ secrets.GH_TOKEN }}
        test: true
        exclude-repos: "2018-09-01-steward"

  # Push Docker images
  docker-push:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags')
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: astrochun
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          astrochun/github-stats-pages:${{ env.RELEASE_VERSION }}
          astrochun/github-stats-pages:latest
          ghcr.io/astrochun/github-stats-pages:${{ env.RELEASE_VERSION }}
          ghcr.io/astrochun/github-stats-pages:latest
